# permissions for end users to view finapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: finapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project
    app.kubernetes.io/part-of: project
    app.kubernetes.io/managed-by: kustomize
  name: finapp-viewer-role
rules:
- apiGroups:
  - tencentcloud.tencentcloud.com
  resources:
  - finapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tencentcloud.tencentcloud.com
  resources:
  - finapps/status
  verbs:
  - get
